# Generated by Django 6.0.4 on 2026-04-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('computer_accessories', 'Computer Accessories'), ('printer_and_scanner', 'Printer and Scanner'), ('others_it_product', "Other's IT Product")], default='computer_accessories', max_length=50)),
                ('category', models.CharField(choices=[('desktop', 'Desktop'), ('monitor', 'Monitor'), ('laptop', 'Laptop'), ('mouse', 'Mouse'), ('wireless_mouse', 'Wireless Mouse'), ('keyboard', 'Keyboard'), ('ups', 'UPS'), ('general_printer', 'General Printer'), ('color_printer', 'Color Printer'), ('dot_printer', 'Dot Printer'), ('sticker_printer', 'Sticker Printer'), ('scanner', 'Scanner'), ('photocopy_machine', 'Photocopy Machine'), ('enroll_scanner', 'Enroll Scanner'), ('ip_phone', 'IP Phone'), ('switch_8port', '8 Port Switch'), ('switch_24port', '24 Port Switch'), ('mc', 'MC'), ('tj_box', 'TJ Box'), ('nvr', 'NVR'), ('ip_camera', 'IP Camera'), ('pendrive', 'Pendrive'), ('usb_hub', 'USB Hub'), ('eth_adapter', 'Eth. Adapter'), ('tv', 'TV'), ('wifi', 'Wifi'), ('virdi_device', 'Virdi Device'), ('network_booster', 'Network Booster'), ('projector', 'Projector'), ('wallstand_screen', 'Wall Stand and Screen')], default='other', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
