# Generated by Django 6.0.4 on 2026-04-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_inventoryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('monitor', 'Monitor'), ('laptop', 'Laptop'), ('mouse', 'Mouse'), ('wireless_mouse', 'Wireless Mouse'), ('keyboard', 'Keyboard'), ('ups', 'UPS'), ('general_printer', 'General Printer'), ('color_printer', 'Color Printer'), ('dot_printer', 'Dot Printer'), ('sticker_printer', 'Sticker Printer'), ('scanner', 'Scanner'), ('photocopy_machine', 'Photocopy Machine'), ('enroll_scanner', 'Enroll Scanner'), ('ip_phone', 'IP Phone'), ('switch_8port', '8 Port Switch'), ('switch_24port', '24 Port Switch'), ('mc', 'MC'), ('tj_box', 'TJ Box'), ('nvr', 'NVR'), ('ip_camera', 'IP Camera'), ('pendrive', 'Pendrive'), ('usb_hub', 'USB Hub'), ('eth_adapter', 'Eth. Adapter'), ('tv', 'TV'), ('wifi', 'Wifi'), ('virdi_device', 'Virdi Device'), ('network_booster', 'Network Booster'), ('projector', 'Projector'), ('wallstand_screen', 'Wall Stand and Screen')], default='other', max_length=50),
        ),
    ]
