# Generated by Django 6.0.4 on 2026-04-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_name', models.CharField(choices=[('shed1', 'NZ Apparels Shed-1'), ('shed2', 'NZ Apparels Shed-2'), ('shed3', 'NZ Apparels Shed-3'), ('it_stock', 'IT Stock Product'), ('all_it', 'All IT Product Inventory')], max_length=50, unique=True)),
                ('row_labels', models.JSONField(default=list)),
                ('column_labels', models.JSONField(default=list)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
