# Generated by Django 6.0.4 on 2026-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.CharField(choices=[('computer_accessories', 'Computer Accessories'), ('printer_and_scanner', 'Printer and Scanner'), ('others_it_product', "Other's IT Product")], default='computer_accessories', max_length=50),
        ),
    ]
