# Generated by Django 5.2.13 on 2026-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_module_alter_shedinventory_shed_name_permission_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
