# Generated by Django 5.2.13 on 2026-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0010_alter_permission_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='action',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='permission',
            name='actions',
            field=models.CharField(blank=True, help_text='Comma separated actions: view,create,edit,delete', max_length=100),
        ),
    ]
